# Experiment with arm64 -- check package install post build

name: check

on:
  #push:
  #pull_request:
  ##release:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    container:
      image: rocker/r2u:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show sources
        run: for f in /etc/apt/sources.list.d/*; do echo "** File is $f"; cat $f; done
      - name: Update
        run: apt update
      - name: Show apt-cache  
        run: apt-cache policy r-cran-digest
      - name: Install
        run: install.r digest
        

          
         

