# Experiment with arm64 -- check package install post build

name: check

on:
  #push:
  #pull_request:
  ##release:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    container:
      image: eddelbuettel/gha_r2u_build:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          apt update
          apt-cache policy r-cran-duckdb
          install.r duckdb
          
         

