# Support arm64 builds 

name: docker

on:
  #push:
  #pull_request:
  #release:
  workflow_dispatch:

jobs:    
  create_builder:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: r2u-builder
          tags: eddelbuettel/r2u_build:noble
          
  create_gha_builder:
    needs: create_builder
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: gha-r2u-builder
          tags: eddelbuettel/gha_r2u_build:noble
          
