# Experiment with arm64 -- one-off builder

name: oneoff

on:
  #push:
  #pull_request:
  ##release:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    container:
      image: eddelbuettel/gha_r2u_build:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Default Config and Cache
        run: |
          r -e 'r2u:::.createDefaultConfiguration()'
          r -e 'r2u:::.loadDB()'
          r -e 'r2u:::.loadAP()'
      - name: Fetch Updated Config
        uses: actions/checkout@v4
        with:
          repository: eddelbuettel/r2u-config
          path: r2u-config
      - name: Copy Updated Config
        run: |
          cp -vax r2u-config/* ~/.local/share/R/r2u
      - name: Upload Config
        uses: actions/upload-artifact@v4.4.0
        with:
          name: r2u_config
          path: ~/.local/share/R/r2u
      #- name: Compute Package Set
      #  run: |
      #    Rscript -e 'options(width=200); r2u::getBuildTargets("/tmp/P.txt", 2500, 25, TRUE)'
      #- name: Upload Package Set
      #  uses: actions/upload-artifact@v4.4.0
      #  with:
      #    name: package_set
      #    path: /tmp/P.txt
          
  make_matrix:
    needs: setup
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    outputs:
      runmatrix: ${{ steps.makematrixstep.outputs.matrixoutput }}
    steps:
      #- name: Get Package Set
      #  uses: actions/download-artifact@v4.1.8
      #  with:
      #    name: package_set
      #    path: /tmp
      #- name: Show Package Set
      #  run: cat /tmp/P.txt
      ## see https://www.kenmuse.com/blog/dynamic-build-matrices-in-github-actions/
      - id: makematrixstep
        run: |
          #TARGETS=$(cat /tmp/P.txt)
          #echo "TARGETS is '$TARGETS'"
          #echo "matrixoutput=$(jq -cn --argjson environments "$TARGETS" '$environments')" >> $GITHUB_OUTPUT        
          # 
          #TARGETS=$(echo '[ "fICA", "bnlearn" ]')
          #TARGETS=$(echo '[ "CaseCohortCoxSurvival", "DriftBurstHypothesis", "strucchangeRcpp" ]')
          #TARGETS=$(echo '[ "Rfast" ]')
          #TARGETS=$(echo '[ "tdata" ]')
          #TARGETS=$(echo '[ "lowpassFilter" ]')
          #TARGETS=$(echo '[ "dbarts" ]')
          #TARGETS=$(echo '[ "GBJ" ]')
          #TARGETS=$(echo '[ "cctools", "comat" ]')
          #TARGETS=$(echo '[ "frab" ]')
          #TARGETS=$(echo '[ "spAbundance" ]')
          #TARGETS=$(echo '[ "GFM" ]')
          #TARGETS=$(echo '[ "hbmem" ]')
          #TARGETS=$(echo '[ "ExactMultinom" ]')
          #TARGETS=$(echo '[ "simts" ]')
          #TARGETS=$(echo '[ "ergm" ]')
          #TARGETS=$(echo '[ "dexter" ]')
          #TARGETS=$(echo '[ "arcgisutils", "wv", "ess" ]')
          #TARGETS=$(echo '[ "POSetR", "sccore", "ijtiff" ]')
          #TARGETS=$(echo '[ "colorfast" ]')
          #TARGETS=$(echo '[ "mniw" ]')
          #TARGETS=$(echo '[ "sphunif", "sdetorus" ]')
          #TARGETS=$(echo '[ "LatticeKrig", "sdsfun" ]')
          #TARGETS=$(echo '[ "SeqNet" ]')
          #TARGETS=$(echo '[ "leidenAlg" ]')
          #TARGETS=$(echo '[ "rminqa" ]')
          #TARGETS=$(echo '[ "iotarelr" ]')
          #TARGETS=$(echo '[ "CMAPSS", "odeGUTS", "dcm2" ]')
          #TARGETS=$(echo '[ "MSEtool" ]')
          #TARGETS=$(echo '[ "tmbstan", "GPFDA" ]')
          #TARGETS=$(echo '[ "tsdistributions", "RationalMatrix" ]')
          #TARGETS=$(echo '[ "tsgarch", "qspray" ]')
          #TARGETS=$(echo '[ "oeli", "processmapR" ]')
          #TARGETS=$(echo '[ "rofanova", "mvp", "symbolicQspray", "weights" ]')
          #TARGETS=$(echo '[ "rstiefel" ]')
          #TARGETS=$(echo '[ "T4cluster" ]')
          #TARGETS=$(echo '[ "latentcor", "fmdu", "nonmem2rx" ]')
          #TARGETS=$(echo '[ "OptCirClust" ]')
          #TARGETS=$(echo '[ "rJava" ]')
          #TARGETS=$(echo '[ "matchingMarkets", "gMCP", "Crossover", "collUtils", "sdpdth" ]')
          #TARGETS=$(echo '[ "cna" ]')
          #TARGETS=$(echo '[ "ICtest" ]')
          #TARGETS=$(echo '[ "qad" ]')
          #TARGETS=$(echo '[ "RDS" ]')
          TARGETS=$(echo '[ "dbarts" ]')
          echo "matrixoutput=$(jq -cn --argjson environments "$TARGETS" '{target: $environments}')" >> $GITHUB_OUTPUT        
          
  package:
    needs: make_matrix
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'eddelbuettel/r2u-arm64-builder'
    container:
      image: eddelbuettel/gha_r2u_build:noble
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.make_matrix.outputs.runmatrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Config
        uses: actions/download-artifact@v4.1.8
        with:
          name: r2u_config
          path: ~/.local/share/R/r2u
      - name: Fetch Updated Config
        uses: actions/checkout@v4
        with:
          repository: eddelbuettel/r2u-config
          path: r2u-config
      - name: Copy Updated depends.dcf
        run: |
          cp -vax r2u-config/depends.dcf r2u-config/blacklist.txt ~/.local/share/R/r2u
      - name: Build
        #run:  r2u.r -v -d -c -f -s .2 -r noble package ${{ matrix.target }}
        run:  r2u.r -v -d -c -f       -r noble package ${{ matrix.target }}
      - name: Check
        run:  test -f /var/local/r2u/ubuntu/pool/dists/noble/main/*.deb
      - name: Upload Deb
        uses: actions/upload-artifact@v4.4.0
        with:
          name: deb-${{ matrix.target }}
          path: /var/local/r2u/ubuntu/pool/dists/noble/main/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: /var/local/r2u/ubuntu/pool/dists/noble/main/*deb
          make_latest: true
          prerelease: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          
         

